name: Build LaTex summary

on: [pull_request]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: change template path
        run: sed '0,/{template}/s//{..}/' -i example/var.tex ;
      - name: build latex pdf
        uses: docker://texlive/texlive:latest
        with:
          args: latexmk (xelatex) -pdf -cd -interaction=nonstopmode -file-line-error -jobname=main -outdir=../build ./example/main.tex
      - name: Archive pdf's as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: compiled-pdf
          path: build/*.pdf
          retention-days: 5
